/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIUniSwapApi.h"

#include "OpenAPIAccountControllerResponse.h"
#include "OpenAPIUniswapInput.h"

namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPIUniSwapApi::AddLiquidityRequest : public Request
{
public:
    virtual ~AddLiquidityRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIUniswapInput OpenAPIUniswapInput;
};

class OPENAPI_API OpenAPIUniSwapApi::AddLiquidityResponse : public Response
{
public:
    virtual ~AddLiquidityResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIUniSwapApi::RemoveLiquidityRequest : public Request
{
public:
    virtual ~RemoveLiquidityRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIUniswapInput OpenAPIUniswapInput;
};

class OPENAPI_API OpenAPIUniSwapApi::RemoveLiquidityResponse : public Response
{
public:
    virtual ~RemoveLiquidityResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIUniSwapApi::SwapExactETHForTokensRequest : public Request
{
public:
    virtual ~SwapExactETHForTokensRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIUniswapInput OpenAPIUniswapInput;
};

class OPENAPI_API OpenAPIUniSwapApi::SwapExactETHForTokensResponse : public Response
{
public:
    virtual ~SwapExactETHForTokensResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIUniSwapApi::SwapExactTokensForTokensRequest : public Request
{
public:
    virtual ~SwapExactTokensForTokensRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIUniswapInput OpenAPIUniswapInput;
};

class OPENAPI_API OpenAPIUniSwapApi::SwapExactTokensForTokensResponse : public Response
{
public:
    virtual ~SwapExactTokensForTokensResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

}
