/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIAbiInput.h"
#include "OpenAPIAbiOutput.h"

namespace MoonSDK
{

/*
 * OpenAPIAbiItem
 *
 * The abi to parse the log object of the contract
 */
class MOONSDK_API OpenAPIAbiItem : public Model
{
public:
    virtual ~OpenAPIAbiItem() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<bool> Anonymous;
	TOptional<bool> Constant;
	TOptional<TArray<OpenAPIAbiInput>> Inputs;
	TOptional<FString> Name;
	TOptional<TArray<OpenAPIAbiOutput>> Outputs;
	TOptional<bool> Payable;
	TOptional<FString> StateMutability;
	FString Type;
	TOptional<double> Gas;
};

}
