/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIBitcoincashApi.h"

#include "OpenAPIAccountControllerResponse.h"
#include "OpenAPIBitcoinCashInput.h"
#include "OpenAPIBitcoinCashTransactionInput.h"

namespace MoonSDK
{

/* 

*/
class MOONSDK_API OpenAPIBitcoincashApi::CreateBitcoinCashAccountRequest : public Request
{
public:
    virtual ~CreateBitcoinCashAccountRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	OpenAPIBitcoinCashInput OpenAPIBitcoinCashInput;
};

class MOONSDK_API OpenAPIBitcoincashApi::CreateBitcoinCashAccountResponse : public Response
{
public:
    virtual ~CreateBitcoinCashAccountResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class MOONSDK_API OpenAPIBitcoincashApi::GetBitcoinCashAccountRequest : public Request
{
public:
    virtual ~GetBitcoinCashAccountRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString AccountName;
};

class MOONSDK_API OpenAPIBitcoincashApi::GetBitcoinCashAccountResponse : public Response
{
public:
    virtual ~GetBitcoinCashAccountResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class MOONSDK_API OpenAPIBitcoincashApi::ListBitcoinCashAccountsRequest : public Request
{
public:
    virtual ~ListBitcoinCashAccountsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
};

class MOONSDK_API OpenAPIBitcoincashApi::ListBitcoinCashAccountsResponse : public Response
{
public:
    virtual ~ListBitcoinCashAccountsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class MOONSDK_API OpenAPIBitcoincashApi::SignBitcoinCashTransactionRequest : public Request
{
public:
    virtual ~SignBitcoinCashTransactionRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString AccountName;
	OpenAPIBitcoinCashTransactionInput OpenAPIBitcoinCashTransactionInput;
};

class MOONSDK_API OpenAPIBitcoincashApi::SignBitcoinCashTransactionResponse : public Response
{
public:
    virtual ~SignBitcoinCashTransactionResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

}
