/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIConveyorFinanceApi.h"

#include "OpenAPIConveyorFinanceControllerResponse.h"
#include "OpenAPITokenSwapParams.h"

namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPIConveyorFinanceApi::SwapRequest : public Request
{
public:
    virtual ~SwapRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPITokenSwapParams OpenAPITokenSwapParams;
};

class OPENAPI_API OpenAPIConveyorFinanceApi::SwapResponse : public Response
{
public:
    virtual ~SwapResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIConveyorFinanceControllerResponse Content;
};

}
