/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIPaymentApi.h"

#include "OpenAPICreatePaymentIntentInput.h"
#include "OpenAPIIWebhook.h"
#include "OpenAPIPaymentIntentResponse.h"

namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPIPaymentApi::MoralisWebhookRequest : public Request
{
public:
    virtual ~MoralisWebhookRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Id;
	OpenAPIIWebhook OpenAPIIWebhook;
};

class OPENAPI_API OpenAPIPaymentApi::MoralisWebhookResponse : public Response
{
public:
    virtual ~MoralisWebhookResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TSharedPtr<FJsonValue> Content;
};

/* 

*/
class OPENAPI_API OpenAPIPaymentApi::PaymentCreatePaymentIntentRequest : public Request
{
public:
    virtual ~PaymentCreatePaymentIntentRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	OpenAPICreatePaymentIntentInput OpenAPICreatePaymentIntentInput;
};

class OPENAPI_API OpenAPIPaymentApi::PaymentCreatePaymentIntentResponse : public Response
{
public:
    virtual ~PaymentCreatePaymentIntentResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIPaymentIntentResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIPaymentApi::PaymentDeletePaymentIntentRequest : public Request
{
public:
    virtual ~PaymentDeletePaymentIntentRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Id;
};

class OPENAPI_API OpenAPIPaymentApi::PaymentDeletePaymentIntentResponse : public Response
{
public:
    virtual ~PaymentDeletePaymentIntentResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIPaymentIntentResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIPaymentApi::PaymentGetAllPaymentIntentsRequest : public Request
{
public:
    virtual ~PaymentGetAllPaymentIntentsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
};

class OPENAPI_API OpenAPIPaymentApi::PaymentGetAllPaymentIntentsResponse : public Response
{
public:
    virtual ~PaymentGetAllPaymentIntentsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TArray<OpenAPIPaymentIntentResponse> Content;
};

/* 

*/
class OPENAPI_API OpenAPIPaymentApi::PaymentGetAvailableChainsRequest : public Request
{
public:
    virtual ~PaymentGetAvailableChainsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class OPENAPI_API OpenAPIPaymentApi::PaymentGetAvailableChainsResponse : public Response
{
public:
    virtual ~PaymentGetAvailableChainsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TArray<FString> Content;
};

/* 

*/
class OPENAPI_API OpenAPIPaymentApi::PaymentGetPaymentIntentRequest : public Request
{
public:
    virtual ~PaymentGetPaymentIntentRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Id;
};

class OPENAPI_API OpenAPIPaymentApi::PaymentGetPaymentIntentResponse : public Response
{
public:
    virtual ~PaymentGetPaymentIntentResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIPaymentIntentResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIPaymentApi::PaymentUpdatePaymentIntentRequest : public Request
{
public:
    virtual ~PaymentUpdatePaymentIntentRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Id;
	OpenAPICreatePaymentIntentInput OpenAPICreatePaymentIntentInput;
};

class OPENAPI_API OpenAPIPaymentApi::PaymentUpdatePaymentIntentResponse : public Response
{
public:
    virtual ~PaymentUpdatePaymentIntentResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIPaymentIntentResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIPaymentApi::TatumWebhookRequest : public Request
{
public:
    virtual ~TatumWebhookRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Id;
	TSharedPtr<FJsonValue> Body;
};

class OPENAPI_API OpenAPIPaymentApi::TatumWebhookResponse : public Response
{
public:
    virtual ~TatumWebhookResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TSharedPtr<FJsonValue> Content;
};

}
