/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITransactionInputMetaData.h"
#include "OpenAPITransactionInputSupportedParams.h"
#include "OpenAPITransactionInputWallet.h"

namespace MoonSDK
{

/*
 * OpenAPITransactionInput
 *
 * 
 */
class MOONSDK_API OpenAPITransactionInput : public Model
{
public:
    virtual ~OpenAPITransactionInput() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPITransactionInputSupportedParams SupportedParams;
	OpenAPITransactionInputWallet Wallet;
	OpenAPITransactionInputMetaData MetaData;
	FString OriginatingHost;
	FString PartnerContext;
	FString Uuid;
	FString Network;
	FString PaymentMethod;
	FString Type;
	double Amount = 0.0;
	FString Destination;
	FString Source;
	FString Onramp;
};

}
