/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

class OPENAPI_API OpenAPISolanaApi
{
public:
	OpenAPISolanaApi();
	~OpenAPISolanaApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class CreateSolanaAccountRequest;
	class CreateSolanaAccountResponse;
	class GetSolanaAccountRequest;
	class GetSolanaAccountResponse;
	class ListSolanaAccountsRequest;
	class ListSolanaAccountsResponse;
	class SignSolanaTransactionRequest;
	class SignSolanaTransactionResponse;
	
    DECLARE_DELEGATE_OneParam(FCreateSolanaAccountDelegate, const CreateSolanaAccountResponse&);
    DECLARE_DELEGATE_OneParam(FGetSolanaAccountDelegate, const GetSolanaAccountResponse&);
    DECLARE_DELEGATE_OneParam(FListSolanaAccountsDelegate, const ListSolanaAccountsResponse&);
    DECLARE_DELEGATE_OneParam(FSignSolanaTransactionDelegate, const SignSolanaTransactionResponse&);
    
    FHttpRequestPtr CreateSolanaAccount(const CreateSolanaAccountRequest& Request, const FCreateSolanaAccountDelegate& Delegate = FCreateSolanaAccountDelegate()) const;
    FHttpRequestPtr GetSolanaAccount(const GetSolanaAccountRequest& Request, const FGetSolanaAccountDelegate& Delegate = FGetSolanaAccountDelegate()) const;
    FHttpRequestPtr ListSolanaAccounts(const ListSolanaAccountsRequest& Request, const FListSolanaAccountsDelegate& Delegate = FListSolanaAccountsDelegate()) const;
    FHttpRequestPtr SignSolanaTransaction(const SignSolanaTransactionRequest& Request, const FSignSolanaTransactionDelegate& Delegate = FSignSolanaTransactionDelegate()) const;
    
private:
    void OnCreateSolanaAccountResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCreateSolanaAccountDelegate Delegate) const;
    void OnGetSolanaAccountResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetSolanaAccountDelegate Delegate) const;
    void OnListSolanaAccountsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListSolanaAccountsDelegate Delegate) const;
    void OnSignSolanaTransactionResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSignSolanaTransactionDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
