/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIDogeCoinApi.h"

#include "OpenAPIAccountAPIResponse.h"
#include "OpenAPIDogeCoinAPIResponse.h"
#include "OpenAPIDogeCoinInput.h"
#include "OpenAPIDogeCoinTransactionInput.h"

namespace MoonSDK
{

/* 

*/
class MOONSDK_API OpenAPIDogeCoinApi::CreateDogeCoinAccountRequest : public Request
{
public:
    virtual ~CreateDogeCoinAccountRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	OpenAPIDogeCoinInput OpenAPIDogeCoinInput;
};

class MOONSDK_API OpenAPIDogeCoinApi::CreateDogeCoinAccountResponse : public Response
{
public:
    virtual ~CreateDogeCoinAccountResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountAPIResponse Content;
};

/* 

*/
class MOONSDK_API OpenAPIDogeCoinApi::GetDogeCoinAccountRequest : public Request
{
public:
    virtual ~GetDogeCoinAccountRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString AccountName;
};

class MOONSDK_API OpenAPIDogeCoinApi::GetDogeCoinAccountResponse : public Response
{
public:
    virtual ~GetDogeCoinAccountResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountAPIResponse Content;
};

/* 

*/
class MOONSDK_API OpenAPIDogeCoinApi::ListDogeCoinAccountsRequest : public Request
{
public:
    virtual ~ListDogeCoinAccountsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
};

class MOONSDK_API OpenAPIDogeCoinApi::ListDogeCoinAccountsResponse : public Response
{
public:
    virtual ~ListDogeCoinAccountsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountAPIResponse Content;
};

/* 

*/
class MOONSDK_API OpenAPIDogeCoinApi::SignDogeCoinTransactionRequest : public Request
{
public:
    virtual ~SignDogeCoinTransactionRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString AccountName;
	OpenAPIDogeCoinTransactionInput OpenAPIDogeCoinTransactionInput;
};

class MOONSDK_API OpenAPIDogeCoinApi::SignDogeCoinTransactionResponse : public Response
{
public:
    virtual ~SignDogeCoinTransactionResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIDogeCoinAPIResponse Content;
};

}
