/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIYearnApi.h"

#include "OpenAPIAccountControllerResponse.h"
#include "OpenAPIInputBody.h"

namespace MoonSDK
{

/* 

*/
class MOONSDK_API OpenAPIYearnApi::AddLiquidityRequest : public Request
{
public:
    virtual ~AddLiquidityRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIInputBody OpenAPIInputBody;
};

class MOONSDK_API OpenAPIYearnApi::AddLiquidityResponse : public Response
{
public:
    virtual ~AddLiquidityResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class MOONSDK_API OpenAPIYearnApi::AddLiquidityWethRequest : public Request
{
public:
    virtual ~AddLiquidityWethRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIInputBody OpenAPIInputBody;
};

class MOONSDK_API OpenAPIYearnApi::AddLiquidityWethResponse : public Response
{
public:
    virtual ~AddLiquidityWethResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class MOONSDK_API OpenAPIYearnApi::RemoveLiquidityRequest : public Request
{
public:
    virtual ~RemoveLiquidityRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIInputBody OpenAPIInputBody;
};

class MOONSDK_API OpenAPIYearnApi::RemoveLiquidityResponse : public Response
{
public:
    virtual ~RemoveLiquidityResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class MOONSDK_API OpenAPIYearnApi::RemoveLiquidityWethRequest : public Request
{
public:
    virtual ~RemoveLiquidityWethRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIInputBody OpenAPIInputBody;
};

class MOONSDK_API OpenAPIYearnApi::RemoveLiquidityWethResponse : public Response
{
public:
    virtual ~RemoveLiquidityWethResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

}
