/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPISellQuote
 *
 * 
 */
class OPENAPI_API OpenAPISellQuote : public Model
{
public:
    virtual ~OpenAPISellQuote() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TArray<FString> Recommendations;
	FString QuoteId;
	FString PaymentMethod;
	FString Ramp;
	double Payout = 0.0;
	double TransactionFee = 0.0;
	double NetworkFee = 0.0;
	double Rate = 0.0;
};

}
