/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITransactionInputSupportedParamsPartnerData.h"
#include "OpenAPITransactionInputSupportedParamsTheme.h"

namespace MoonSDK
{

/*
 * OpenAPITransactionInputSupportedParams
 *
 * 
 */
class MOONSDK_API OpenAPITransactionInputSupportedParams : public Model
{
public:
    virtual ~OpenAPITransactionInputSupportedParams() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPITransactionInputSupportedParamsPartnerData PartnerData;
	OpenAPITransactionInputSupportedParamsTheme Theme;
};

}
