/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIAbiItem.h"
#include "OpenAPIBlock.h"
#include "OpenAPIIERC20Approval.h"
#include "OpenAPIIERC20Transfer.h"
#include "OpenAPIINFTApproval.h"
#include "OpenAPIINFTTransfer.h"
#include "OpenAPIINativeBalance.h"
#include "OpenAPIIOldNFTApproval.h"
#include "OpenAPIInternalTransaction.h"
#include "OpenAPILog.h"
#include "OpenAPITransaction.h"

namespace MoonSDK
{

/*
 * OpenAPIIWebhook
 *
 * 
 */
class MOONSDK_API OpenAPIIWebhook : public Model
{
public:
    virtual ~OpenAPIIWebhook() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPIBlock Block;
	FString ChainId;
	TArray<OpenAPILog> Logs;
	TArray<OpenAPITransaction> Txs;
	TArray<OpenAPIInternalTransaction> TxsInternal;
	TArray<OpenAPIAbiItem> Abi;
	double Retries = 0.0;
	bool Confirmed = false;
	FString Tag;
	FString StreamId;
	TArray<OpenAPIIERC20Transfer> Erc20Transfers;
	TArray<OpenAPIIERC20Approval> Erc20Approvals;
	TArray<OpenAPIINFTTransfer> NftTransfers;
	TArray<OpenAPIINativeBalance> NativeBalances;
	OpenAPIIOldNFTApproval NftApprovals;
	TArray<OpenAPIINFTApproval> NftTokenApprovals;
};

}
