/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIGetSupportedOnRampsResponseMessageInnerIconsPng.h"

namespace MoonSDK
{

/*
 * OpenAPIGetSupportedOnRampsResponseMessageInnerIcons
 *
 * 
 */
class MOONSDK_API OpenAPIGetSupportedOnRampsResponseMessageInnerIcons : public Model
{
public:
    virtual ~OpenAPIGetSupportedOnRampsResponseMessageInnerIcons() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPIGetSupportedOnRampsResponseMessageInnerIconsPng Png;
	FString Svg;
};

}
