/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITriggerOutput.h"

namespace OpenAPI
{

/*
 * OpenAPILog
 *
 * 
 */
class OPENAPI_API OpenAPILog : public Model
{
public:
    virtual ~OpenAPILog() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TArray<OpenAPITriggerOutput>> Triggers;
	FString LogIndex;
	FString TransactionHash;
	FString Address;
	FString Data;
	FString Topic0;
	FString Topic1;
	FString Topic2;
	FString Topic3;
};

}
