/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIGetSupportedOnRampsResponseMessageInnerIcons.h"

namespace OpenAPI
{

/*
 * OpenAPIGetSupportedOnRampsResponseMessageInner
 *
 * 
 */
class OPENAPI_API OpenAPIGetSupportedOnRampsResponseMessageInner : public Model
{
public:
    virtual ~OpenAPIGetSupportedOnRampsResponseMessageInner() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Id;
	FString DisplayName;
	OpenAPIGetSupportedOnRampsResponseMessageInnerIcons Icons;
	FString Icon;
};

}
