/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITransactionRequest.h"
#include "OpenAPITx.h"

namespace OpenAPI
{

/*
 * OpenAPITransaction
 *
 * 
 */
class OPENAPI_API OpenAPITransaction : public Model
{
public:
    virtual ~OpenAPITransaction() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> MoonScanUrl;
	FString TransactionHash;
	FString SignedTransaction;
	TOptional<FString> SignedMessage;
	TOptional<FString> RawTransaction;
	TOptional<FString> Signature;
	TOptional<TMap<FString, OpenAPITx>> Transaction;
	TOptional<TArray<OpenAPITransactionRequest>> UserOps;
	TOptional<FString> UseropTransaction;
};

}
