/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIINFTApprovalERC1155.h"
#include "OpenAPIINFTApprovalERC721.h"

namespace MoonSDK
{

/*
 * OpenAPIIOldNFTApproval
 *
 * 
 */
class MOONSDK_API OpenAPIIOldNFTApproval : public Model
{
public:
    virtual ~OpenAPIIOldNFTApproval() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TArray<OpenAPIINFTApprovalERC721> ERC721;
	TArray<OpenAPIINFTApprovalERC1155> ERC1155;
};

}
