/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPITransactionRequest
 *
 * 
 */
class OPENAPI_API OpenAPITransactionRequest : public Model
{
public:
    virtual ~OpenAPITransactionRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> Nonce;
	TOptional<FString> Data;
	TOptional<FString> Value;
	TOptional<FString> To;
	TOptional<FString> From;
	TOptional<FString> MaxFeePerGas;
	TOptional<FString> MaxPriorityFeePerGas;
};

}
