/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace MoonSDK
{

/*
 * OpenAPITransactionResponseInfo
 *
 * 
 */
class MOONSDK_API OpenAPITransactionResponseInfo : public Model
{
public:
    virtual ~OpenAPITransactionResponseInfo() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString ConveyorGas;
	FString AffiliateGas;
	FString AffiliateAggregator;
	FString AmountOut;
	FString AmountOutMin;
};

}
