/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace MoonSDK
{

class MOONSDK_API OpenAPITronApi
{
public:
	OpenAPITronApi();
	~OpenAPITronApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class CreateTronAccountRequest;
	class CreateTronAccountResponse;
	class GetTronAccountRequest;
	class GetTronAccountResponse;
	class ListTronAccountsRequest;
	class ListTronAccountsResponse;
	class SignTronTransactionRequest;
	class SignTronTransactionResponse;
	
    DECLARE_DELEGATE_OneParam(FCreateTronAccountDelegate, const CreateTronAccountResponse&);
    DECLARE_DELEGATE_OneParam(FGetTronAccountDelegate, const GetTronAccountResponse&);
    DECLARE_DELEGATE_OneParam(FListTronAccountsDelegate, const ListTronAccountsResponse&);
    DECLARE_DELEGATE_OneParam(FSignTronTransactionDelegate, const SignTronTransactionResponse&);
    
    FHttpRequestPtr CreateTronAccount(const CreateTronAccountRequest& Request, const FCreateTronAccountDelegate& Delegate = FCreateTronAccountDelegate()) const;
    FHttpRequestPtr GetTronAccount(const GetTronAccountRequest& Request, const FGetTronAccountDelegate& Delegate = FGetTronAccountDelegate()) const;
    FHttpRequestPtr ListTronAccounts(const ListTronAccountsRequest& Request, const FListTronAccountsDelegate& Delegate = FListTronAccountsDelegate()) const;
    FHttpRequestPtr SignTronTransaction(const SignTronTransactionRequest& Request, const FSignTronTransactionDelegate& Delegate = FSignTronTransactionDelegate()) const;
    
private:
    void OnCreateTronAccountResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCreateTronAccountDelegate Delegate) const;
    void OnGetTronAccountResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetTronAccountDelegate Delegate) const;
    void OnListTronAccountsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListTronAccountsDelegate Delegate) const;
    void OnSignTronTransactionResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSignTronTransactionDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
