/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIAbiInput
 *
 * 
 */
class OPENAPI_API OpenAPIAbiInput : public Model
{
public:
    virtual ~OpenAPIAbiInput() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Name;
	FString Type;
	TOptional<bool> Indexed;
	TOptional<TArray<OpenAPIAbiInput>> Components;
	TOptional<FString> InternalType;
};

}
