/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIBitcoinCashTransactionInput
 *
 * 
 */
class OPENAPI_API OpenAPIBitcoinCashTransactionInput : public Model
{
public:
    virtual ~OpenAPIBitcoinCashTransactionInput() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> To;
	TOptional<double> Value;
	TOptional<FString> Network;
	TOptional<bool> Compress;
};

}
