/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIInputBody.h"
#include "OpenAPITransaction.h"
#include "OpenAPITransactionData.h"
#include "OpenAPITransactionResponse.h"
#include "OpenAPITransactionResponseTx.h"

namespace MoonSDK
{

/*
 * OpenAPIConveyorFinanceControllerResponse
 *
 * 
 */
class MOONSDK_API OpenAPIConveyorFinanceControllerResponse : public Model
{
public:
    virtual ~OpenAPIConveyorFinanceControllerResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIInputBody> Input;
	TOptional<OpenAPITransactionResponse> Convey;
	TOptional<OpenAPITransactionData> Data;
	TOptional<OpenAPITransactionResponseTx> Tx;
	TOptional<OpenAPITransaction> _Signed;
	bool Success = false;
	FString Message;
};

}
