/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIAaveApi.h"

#include "OpenAPIAaveInput.h"
#include "OpenAPIAccountControllerResponse.h"

namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPIAaveApi::BorrowRequest : public Request
{
public:
    virtual ~BorrowRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIAaveInput OpenAPIAaveInput;
};

class OPENAPI_API OpenAPIAaveApi::BorrowResponse : public Response
{
public:
    virtual ~BorrowResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIAaveApi::LendRequest : public Request
{
public:
    virtual ~LendRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIAaveInput OpenAPIAaveInput;
};

class OPENAPI_API OpenAPIAaveApi::LendResponse : public Response
{
public:
    virtual ~LendResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIAaveApi::RepayRequest : public Request
{
public:
    virtual ~RepayRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIAaveInput OpenAPIAaveInput;
};

class OPENAPI_API OpenAPIAaveApi::RepayResponse : public Response
{
public:
    virtual ~RepayResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIAaveApi::UserReserveDataRequest : public Request
{
public:
    virtual ~UserReserveDataRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString Authorization;
	FString Name;
	OpenAPIAaveInput OpenAPIAaveInput;
};

class OPENAPI_API OpenAPIAaveApi::UserReserveDataResponse : public Response
{
public:
    virtual ~UserReserveDataResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIAccountControllerResponse Content;
};

}
