/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITransactionResponseInfo.h"
#include "OpenAPITransactionResponseTx.h"

namespace OpenAPI
{

/*
 * OpenAPITransactionResponse
 *
 * 
 */
class OPENAPI_API OpenAPITransactionResponse : public Model
{
public:
    virtual ~OpenAPITransactionResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Message;
	OpenAPITransactionResponseTx Tx;
	OpenAPITransactionResponseInfo Info;
	double ChainId = 0.0;
	double CurrentBlockNumber = 0.0;
};

}
