/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPISupportedAssetResponseAssetsInner.h"

namespace OpenAPI
{

/*
 * OpenAPISupportedAssetResponse
 *
 * 
 */
class OPENAPI_API OpenAPISupportedAssetResponse : public Model
{
public:
    virtual ~OpenAPISupportedAssetResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Country;
	TArray<OpenAPISupportedAssetResponseAssetsInner> Assets;
};

}
