/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITriggerOutput.h"

namespace MoonSDK
{

/*
 * OpenAPIIERC20Transfer
 *
 * 
 */
class MOONSDK_API OpenAPIIERC20Transfer : public Model
{
public:
    virtual ~OpenAPIIERC20Transfer() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString TransactionHash;
	FString Contract;
	FString LogIndex;
	FString From;
	FString To;
	FString Value;
	FString TokenDecimals;
	FString TokenName;
	FString TokenSymbol;
	TOptional<FString> ValueWithDecimals;
	TOptional<TArray<OpenAPITriggerOutput>> Triggers;
};

}
