/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "MoonSDKModule.h"

IMPLEMENT_MODULE(MoonSDKModule, MoonSDK);
DEFINE_LOG_CATEGORY(LogMoonSDK);

void MoonSDKModule::StartupModule()
{
}

void MoonSDKModule::ShutdownModule()
{
}
