/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPISupportedDefaultResponseDefaultsId.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPISupportedDefaultResponseDefaultsId::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("provider")); WriteJsonValue(Writer, Provider);
	Writer->WriteIdentifierPrefix(TEXT("paymentMethod")); WriteJsonValue(Writer, PaymentMethod);
	Writer->WriteIdentifierPrefix(TEXT("amount")); WriteJsonValue(Writer, Amount);
	Writer->WriteIdentifierPrefix(TEXT("target")); WriteJsonValue(Writer, Target);
	Writer->WriteIdentifierPrefix(TEXT("source")); WriteJsonValue(Writer, Source);
	Writer->WriteObjectEnd();
}

bool OpenAPISupportedDefaultResponseDefaultsId::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("provider"), Provider);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("paymentMethod"), PaymentMethod);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("amount"), Amount);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("target"), Target);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("source"), Source);

	return ParseSuccess;
}

}
