/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIIOldNFTApproval.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIIOldNFTApproval::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("ERC721")); WriteJsonValue(Writer, ERC721);
	Writer->WriteIdentifierPrefix(TEXT("ERC1155")); WriteJsonValue(Writer, ERC1155);
	Writer->WriteObjectEnd();
}

bool OpenAPIIOldNFTApproval::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("ERC721"), ERC721);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("ERC1155"), ERC1155);

	return ParseSuccess;
}

}
