/**
 * moon-vault-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIBitcoinCashTransactionOutput.h"

#include "MoonSDKModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace MoonSDK
{

void OpenAPIBitcoinCashTransactionOutput::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (SignedTx.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("signedTx")); WriteJsonValue(Writer, SignedTx.GetValue());
	}
	if (TransactionHash.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("transaction_hash")); WriteJsonValue(Writer, TransactionHash.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIBitcoinCashTransactionOutput::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("signedTx"), SignedTx);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("transaction_hash"), TransactionHash);

	return ParseSuccess;
}

}
